@startuml

class Controller {
  playButtonPress()
  nextButtonPress()
  prevButtonPress()
  nextAlbum()
  prevAlbum()
}

class Play {
  play(speed)
  pause()
  stop()
  next()
  prev()
  goto()
  status()
}

class Album {
  set()
  get()
  preload(firstSlide, lastSlide)
}

class Slide {
  load()
}

class Photo {
  load()
}

class Transition {
}

Controller "1..*" <-- "1" Play
Play "1" o-- "1" Album
Album "1" o-- "*" Slide
Slide "1" o-- "*" Photo
Slide "1" o-- "*" Transition

@enduml