// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"]('../app'));

  app.listen(process.env.PORT || 3000);

}).call(this);

//# sourceMappingURL=index.map
